services:
  # ----------------------------------
  # 1️⃣ FastAPI Web Service
  # ----------------------------------
  - type: web
    name: news-api
    runtime: docker
    dockerfilePath: ./Dockerfile.web
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: OLLAMA_BASE_URL
        value: http://news-digest:11434
      - key: OLLAMA_MODEL
        value: gemma3:1b
      - key: RSS_FETCH_TIMEOUT
        value: "30"
      - key: RSS_MAX_ARTICLES_PER_FEED
        value: "10"
      - key: MORNING_DELIVERY_HOUR
        value: "8"
      - key: EVENING_DELIVERY_HOUR
        value: "18"
      - key: DELIVERY_TIMEZONE
        value: Asia/Calcutta
      - key: LOG_LEVEL
        value: INFO
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: WHATSAPP_RECIPIENT_NUMBER
        sync: false

  # ----------------------------------
  # 2️⃣ Ollama Worker (News Digest)
  # ----------------------------------
  - type: worker
    name: news-digest
    runtime: docker
    dockerfilePath: ./Dockerfile.digest
    plan: starter
    autoDeploy: true
    envVars:
      - key: OLLAMA_MODEL
        value: gemma3:1b
      - key: DIGEST_SCRIPT_PATH
        value: /app/send_digest.py   # ✅ FIXED PATH
      - key: MORNING_DELIVERY_HOUR
        value: "8"
      - key: EVENING_DELIVERY_HOUR
        value: "18"
      - key: DELIVERY_TIMEZONE
        value: Asia/Calcutta
      - key: LOG_LEVEL
        value: INFO
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: WHATSAPP_RECIPIENT_NUMBER
        sync: false
